[package]
name = "xcp"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.76"

authors = ["Vector Informatik GmbH, RDM"]
description = "XCP for Rust, based on XCPlite"
readme = "README.md"
keywords = ["XCP","Rust","Vector","ASAM","CANape","A2L"]
license = "MIT OR Apache-2.0"
homepage = "https://vector.com"  
repository = "https://github.com/vectorgrp/xcp-lite"
categories = ["MC"] 

[workspace]
members = [    
    "xcp_client",  
      
    "examples/hello_xcp",
    "examples/single_thread_demo",
    "examples/multi_thread_demo",
    "examples/protobuf_demo",
    "examples/point_cloud_demo",
    "examples/rayon_demo",
    "examples/tokio_demo",
    "examples/type_description_demo",
    "examples/xcp_idl_generator_demo",     
]



[[example]]
name = "xcp_client"
path = "xcp_client/src/main.rs"

[[example]]
name = "hello_xcp"
path = "examples/hello_xcp/src/main.rs"

[[example]]
name = "single_thread_demo"
path = "examples/single_thread_demo/src/main.rs"

[[example]]
name = "multi_thread_demo"
path = "examples/multi_thread_demo/src/main.rs"

[[example]]
name = "rayon_demo"
path = "examples/rayon_demo/src/main.rs"

[[example]]
name = "tokio_demo"
path = "examples/tokio_demo/src/main.rs"

[[example]]
name = "point_cloud_demo"
path = "examples/point_cloud_demo/src/main.rs"

[[example]]
name = "scoped_threads"
path = "examples/scoped_threads/src/main.rs"

[[example]]
name = "protobuf_demo"
path = "examples/protobuf_demo/src/main.rs"


[features]

# Feature xcp_server enables the build in XCP server 
xcp_server = []

# Feature json enables dependency to serde and serde_json
# json = ["dep:serde","dep:serde_json"]
json = []

# Feature a2l_gen to enable automatic registry entries for calibration page structs
auto_reg = ["dep:xcp_type_description_derive","dep:xcp_type_description"]

# Feature a2l_reader to enable automatic check of the generated A2L file
# Also needed to build the xcp_client demo application
a2l_reader = ["dep:a2lfile"]

#default = ["json","auto_reg","xcp_server"]
default = ["auto_reg","xcp_server"]


[dependencies]

# Command line parser
clap = { version = "4.5.9", features = ["derive"] }

# Rust macro to automatically implement the builder pattern for arbitrary structs
derive_builder = "0.20.0"

# Raw FFI bindings to platform libraries like libc
libc = "0.2.153"

# A macro to generate structures which behave like bitflags
bitflags = "2.6.0"

# Logging
log = "0.4.21"
env_logger = "0.11.3"

# Collects build-information of your Rust crate
# used to generate EPK
# build-info = "0.0.36"

# A generic serialization/deserialization framework
# Used to handle json parameter files (optional)
# Used in point_cloud_demo
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

# Binary serialization strategies for transforming structs into bytes
# bincode = "1.3.3"
cdr = "0.2.4"

# A macro for declaring lazily evaluated statics
lazy_static = "1.4.0"

# Single assignment cells
once_cell = "1.19.0"
static_cell = "2.1.0"

# More compact and efficient implementations of the standard synchronization primitives
# Used for the mutex in CalSeg::sync()
parking_lot = "0.12.3"

# proc-macro A2L serializer for structs
xcp_type_description  = { path = "./xcp_type_description/", optional = true}
xcp_type_description_derive = { path = "./xcp_type_description/xcp_type_description_derive/", optional = true }

# proc-macro IDL generator
xcp_idl_generator  = { path = "./xcp_idl_generator/"}
xcp_idl_generator_derive  = { path = "./xcp_idl_generator/xcp_idl_generator_derive/"}

# A2L reader
a2lfile = { version="2.2.0", optional = true}



[dev-dependencies]

# XCP test client
tokio = { version = "1.37.0", features = ["full"] }
a2lfile = "2.2.0"
bytes = "1.6.0"
byteorder = "1.5.0"
xcp_client = { path = "xcp_client" }

# dependencies for rayon demo example
rayon = "1.10.0"
num = "0.4.3"
image = "0.25.2"

# dependencies for protobuf demo example
prost = "0.13.1"
prost-types = "0.13.1"

# benchmarking
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "xcp_benchmark"
harness = false


[build-dependencies]
cc = "1.0"
build-info-build = "0.0.36"

# generate interface to XCPlite
bindgen = "0.69.4"


[profile.dev.package."*"]
debug = false
opt-level = 3

[profile.dev]
# panic = 'abort'
# lto = true
debug = true
opt-level = 2

[profile.release]
panic = 'abort'
debug = true
lto = true
opt-level = 3
