[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
xcp = { path = "../../", features = ["auto_reg","json"] }
xcp_idl_generator = { path = "../../xcp_idl_generator/"}
xcp_idl_generator_derive = { path = "../../xcp_idl_generator/xcp_idl_generator_derive/" }



