[package]
name = "tokio_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
chrono = "0.4.38"
lazy_static = "1.4.0"
tokio = { version = "1.37.0", features = ["full"] }

xcp = { path = "../../", features = ["auto_reg","json"] }
xcp_type_description  = { path = "../../xcp_type_description/"}
xcp_type_description_derive = { path = "../../xcp_type_description/xcp_type_description_derive/" }

