[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
characteristic_container = { path = "../characteristic_container" }
characteristic_container_derive = { path = "../characteristic_container/characteristic_container_derive" }