[package]
name = "tokio_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
rayon = "1.10.0"
# chrono = "0.4.38"
lazy_static = "1.4.0"
# paste = "1.0.14"
xcp = { path = "../../" }
#xcp = { git = "https://github.com/vectorgrp/xcp-lite" }



[profile.dev.package."*"]
debug = false
opt-level = 3

[profile.dev]
panic = 'abort'
debug = true
lto = true
opt-level = 2


